### ISSUE TITLE
Login issues after upgrade

### ISSUE THREAD

**Issue by ourherald** [giterlizzi/dokuwiki-plugin-bootswrapper#105]
Sorry if I mess this up; it's my first bug report.

After upgrading bootstrap3 from v2018-02-16 to v2019-05-22, I was no longer able to login to my wiki. When the login button was clicked, the page's header appeared, but no fields to enter creds.

The nginx error log gave me this:
`2019/10/13 15:23:12 [error] 3830#3830: *399 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function dokuwiki\template\bootstrap3\simplexml_load_file() in /var/www/dokuwiki/lib/tpl/bootstrap3/Temp
late.php:2530`

Switching to a different template (which had to be done by manually editing local.php) restored the ability to log in and reverting to bootstrap3 v2018-02-16 likewise resolved the issue.

Not sure if it matters, but I use the ACL Manager and Active Directory Auth plugins, so maybe there's an interaction there that's going awry. I'm running this on an Ubuntu 18.04 VM with nginx and php-7.2.

I hope this helps somehow; if there's anymore info you need, please do let me know. And thanks for a great template!

**Comment by giterlizzi** [comment]
Hi, seems you have a missing PHP module (SimpleXML). Please verify if you have `php-xml` module installed in your system (eg. `php -m | grep -i xml`).

Joseph

**Comment by ourherald** [comment]
Hi, Joseph—you hit the nail on the head! I installed `php-xml`, upgraded to the latest version, and everything works perfectly. Sorry for being such an idiot about this stuff; php must just be over my head. Thanks again for your hard work.
