### ISSUE TITLE
Update plugin to use Material Design Icons

### ISSUE THREAD

**Issue by TrapSpace** [giterlizzi/dokuwiki-plugin-bootswrapper#107]
@giterlizzi Since you recently changed the Bootstrap3 template to use Material Design Icons (in the develop branch) this broke the icons in this Bootswrapper plugin. 

Suggestion would be the update this plugin to work on MDI too. 

P.S. If you don't have the time, give me a couple of points on how to update it and I'll work on it and send you a pull request if you like. 

Cheers

**Comment by giterlizzi** [comment]
Hi @TrapSpace
I have plan to switch to inline SVG icons or force "Icons" plugin dependency.

I suggest this workaround,

    install or upgrade https://www.dokuwiki.org/plugin:icons
    enable icons>loadFontAwesome option

Joseph

**Comment by TrapSpace** [comment]
Hi @giterlizzi 

Thanks for your quick reply and the workaround. I look forward to your next updates. 

Cheers

**Comment by giterlizzi** [comment]
Added in latest BS3 template a compatibility layer for FontAwesome icons.
