### ISSUE TITLE
info/icon callouts at top of page don't wrap properly with TOC displayed.

### ISSUE THREAD

**Issue by listerr** [giterlizzi/dokuwiki-plugin-bootswrapper#110]
Hi,

When I have a callout at the top of the page e.g.:

```
<callout type="info" icon="true">
=== Title of callout ===
some text here
</callout>
```

When the TOC is displayed, it doesn't appear to wrap correctly.

![image](https://user-images.githubusercontent.com/3037635/73867549-d65fdb80-483e-11ea-88d2-f5200263c8da.png)

If I just use the default callout with no settings, it displays properly when the TOC is expanded:-

![image](https://user-images.githubusercontent.com/3037635/73867987-977e5580-483f-11ea-9f86-360144e0ddb3.png)

If I add an icon= to this callout, then the wrapping problem returns.

Any suggestion how to fix this?

Thanks,

**Comment by dolandemort** [comment]
Check [this](https://github.com/giterlizzi/dokuwiki-plugin-bootswrapper/issues/99) thread out for the solution.

**Comment by listerr** [comment]
Thanks for that!. Added that suggestion into the userstyle.css and it works fine.
