### ISSUE TITLE
Button: External link not working, icons neither

### ISSUE THREAD

**Issue by fibinicci** [giterlizzi/dokuwiki-plugin-bootswrapper#111]
Hi 
I am just creating simple buttons where I want the link to be a url not an internal wiki page.
It simply does not take me to the url, instead it points to "This topics does not exist yet" like when it points to an internal page.

Additionally, the glyphicons or Font Awesome do not show up either.
and no size, nor type is taken into account

Here is what I am testing with syntax "button" or "btn":
`<button type="link" size="lg" icon="fa-trash-o">[[https://www.dokuwiki.org|HELP]]</button>`

Where should I investigate? thanks

**Comment by giterlizzi** [comment]
Uhmm... seems the corrected standard DokuWiki syntax for external links.

For display the icon prepend "fa" class (eg. "fa fa-house").

Joseph

**Comment by fibinicci** [comment]
Hi
I come back to above mentioned issue

The hyperlink to external website now works in my buttons (don't know what has changed as i am still on the previous theme release)

However I still cannot format / apply styles to these buttons , whatever I do they do not accept type , icons, etc....

Recently i started to use <panel> and they work great : style is applied , icons inserted etc...

If it works for panels, why not for buttons?
Am really confused
I have taken your syntax examples and did several tests but nothing makes these buttons change.

Any suggestions?
thanks in advance
Grazie
fred

**Comment by fibinicci** [comment]
As mentioned in #516 I discovered the conflict: it came from Web components pluging (from Gerard Nico)
