### ISSUE TITLE
Warnings after updating to Hogfather

### ISSUE THREAD

**Issue by Miro-Collas** [giterlizzi/dokuwiki-plugin-bootswrapper#116]
I am seeing this in the server log...

`PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74 PHP message: PHP Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTE" while reading upstream`

**Comment by giterlizzi** [comment]
Hi,
seems this is a problem with DokuWiki Lexer class (is not loaded properly).
Do you have problems with other plugins?

**Comment by Miro-Collas** [comment]
> Hi,
> seems this is a problem with DokuWiki Lexer class (is not loaded properly).
> Do you have problems with other plugins?

No, I don't. Nothing that I have observed, at last.

**Comment by giterlizzi** [comment]
splitbrain/dokuwiki#3132

**Comment by giterlizzi** [comment]
This issue was resolved with a DokuWiki fix.

splitbrain/dokuwiki#3146
splitbrain/dokuwiki#3132

Please update your "Hogfather" installation.

Joseph
