### ISSUE TITLE
Accordion doesn't work with Hogfather RC3

### ISSUE THREAD

**Issue by CaseUndefined** [giterlizzi/dokuwiki-plugin-bootswrapper#120]
Hi there,
I'm running Hogfather RC3 and Bootstrap 3 (2020-04-04) and Bootstrap Wrapper (2017-04-07). After the update all Accordions fail to open.

Regards

**Comment by intervisionlord** [comment]
Same issue for me

```
TypeError: can't convert o to string 2 js.php:1:131003
    test self-hosted:2739
    l https://*********/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    jQuery 2
        each
        each
    l https://*********/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    <анонимный> https://wiki.twr.su/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    jQuery 2
        dispatch
        handle
```

**Comment by ics01** [comment]
I have the same problem, Accordeon do not work since the new version Hogfather RC3 (this version is causing a lot of troubles with other extensions of dokuwiki, hope you'll have a RC4 in a couple of days ! ;-) )

Anyway, Accordion do not display error message, but only a grey box, without opening ability.

Thanks.

**Comment by n0dai** [comment]
A quick fix can be to use the old **scripts** folder from the stable branch. **jquery-migrate** was removed since Hogfather.

**Comment by ics01** [comment]
Thanks to n0dai for this quick-fix answer, it works perfectly.
There was many troubles with Hogfather RC3, it is not common with dokuwiki.

**Comment by giterlizzi** [comment]
Today have released a Hogfather-compatible version.

Other notable feature:
- Syntax help in popup
- PSR-2 support
- Popup support for non-standard DokuWiki installation (es. Docker, Debian, etc.)

Enjoy!
