### ISSUE TITLE
Incompatible with HogFather 5.3!

### ISSUE THREAD

**Issue by Capbat99** [giterlizzi/dokuwiki-plugin-bootswrapper#121]
Very Few fonctionality works with HogFather 5.3 Example Buttons.

**Comment by n0dai** [comment]
A quick fix can be to use the old **scripts** folder from the stable branch. **jquery-migrate** was removed since Hogfather. It's working for me.

**Comment by FloMiLe** [comment]
@n0dai That does not do it for me. I would also be cautious since I don't know whether have been other changes that hogfather depends on.

**Comment by giterlizzi** [comment]
Today have released a Hogfather-compatible version.

Other notable feature:
- Syntax help in popup
- PSR-2 support
- Popup support for non-standard DokuWiki installation (es. Docker, Debian, etc.)

Enjoy!
