### ISSUE TITLE
Javascript Problems after hogfather update

### ISSUE THREAD

**Issue by gareth-johnstone** [giterlizzi/dokuwiki-plugin-bootswrapper#125]
We have the following code
```
<nav type="tabs">
  * [[#tab-exports|Exports]]
  * [[#tab-imports|Imports]]
  * [[#tab-queries|Queries]]
  * [[#tab-fields|Fields]]
  * [[#tab-fieldtypes|Field Types]]
  * [[#tab-substitutions|Substitutions]]
  * [[#tab-formatting|Text & Data Formatting]]
  * [[#tab-structure|Structure]]
  * [[#tab-logging|Logging]]

 
<pane id="tab-exports">
...
```

Before the hogfather update this displayed tabs at the top of the page and showed the correct clicked on pane

However, since updating we are now getting the following behaviour, where the tabs are now in a list and all the pains are showing

Bootstrap 3 theme:
![image](https://user-images.githubusercontent.com/13420337/91560273-7a22ed00-e931-11ea-93cc-42a9014b6c69.png)

Default DokuWiki theme:
![image](https://user-images.githubusercontent.com/13420337/91560406-bb1b0180-e931-11ea-858c-cd92ee8d086c.png)

I have checked the developer console and can see the following: (the file in question is: `.../lib/exe/js.php?t=bootstrap3&tseed=x`)
![image](https://user-images.githubusercontent.com/13420337/91560721-32e92c00-e932-11ea-9980-c4fba155882b.png)
Which on closer inspection is related to this:
![image](https://user-images.githubusercontent.com/13420337/91560774-498f8300-e932-11ea-95f6-6d7dbd2614b6.png)

Any help on the matter would be greatly appreciated.

**Comment by giterlizzi** [comment]
Hi,
seems a problem with JS defer attribute. Hogfather introduce the defer attribute for speedup the JS scripts. You can:
- disable ``defer_js`` option in Configuration Settings
- update Bootstrap3 Template to latest release with the support to Hogfather (today will be rolled out another release with improvments)
