### ISSUE TITLE
Minor Cosmetic Issues with Latest Release

### ISSUE THREAD

**Issue by Miro-Collas** [giterlizzi/dokuwiki-plugin-bootswrapper#126]
### Description

Yesterday, we finally updated both our dokuwiki and boostrap. Some minor issues have emerged.

- Using <nav type="tabs">, the currently selected tab isn't formatted properly. See attached snapshot.
- On pages, there used to be a link symbol which could be clicked to get the URL of the anchor of the header; that link has gone. Not sure if that's a template issue, or something that changed with Hogfather.

### Versions

* Bootstrap3 Template: 2020-08-28
* DokuWiki: 2020-08-28

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample page or snippet
![Navbar](https://user-images.githubusercontent.com/39207573/91629722-68753000-e999-11ea-8989-9ee265050013.png)

```
<nav type="tabs">
  * [[start|English]]
  * [[index_de|Deutsch]]
  * [[index_es|Español]]
  * [[index_fr|Francophone]]
  * [[index_it|Italiano]]
  * [[index_nl|Nederlands]]
  * [[index_pl|Polski]]
  * [[index_ru|Русский]]
</nav>
```

**Comment by verliber** [comment]
About links — you can fix problem, if edit file `lib/tpl/bootstrap3/script.js`
You need to add a line:
```dw_template.anchorJS();```
after that's code:
```
 var dw_template = {

    init: function () {

        dw_template.common();
        dw_template.mobileLayout();
        dw_template.toc();
         ...
        dw_template.menuitem();
        dw_template.cookieLaw();
        dw_template.plugins();
```

That fixed my problem.

**Comment by Miro-Collas** [comment]
Aha, thanks for the tip! :-)
