### ISSUE TITLE
Text "align" does not work

### ISSUE THREAD

**Issue by Conny64** [giterlizzi/dokuwiki-plugin-bootswrapper#129]
Hi,
I try to center a text by using following syntax:

``
<text type="danger" size="60px" background="info" align="center" transform="uppercase">NEU - Inhalt kommt noch </text>
``

but the align does not work

**Comment by giterlizzi** [comment]
Hi,
the align option work only for "block" element.

Change the syntax from ```<text>``` to ```<TEXT>```.
