### ISSUE TITLE
Edit button for every panel in an accordion 

### ISSUE THREAD

**Issue by sceptiq** [giterlizzi/dokuwiki-plugin-bootswrapper#65]
## great great stuff!

Not an issue - just a thought...

working on accordions with many panels it would be nice to have a edit button to jump dirctly inside of a panel.. :) .. and stay more focused! just a tiny one maybe? :)

**Comment by LotarProject** [comment]
Hi @sceptiq, i have added section edit support for "panel" and "pane" syntax.

Joseph
