### ISSUE TITLE
Button toolbar 

### ISSUE THREAD

**Issue by flanesi** [giterlizzi/dokuwiki-plugin-bootswrapper#71]
When I click on Bootstrap Wrapper button in toolbar, i have this error:

500 internal server error

> 
> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at postmaster@flanesi.it to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.

**Comment by LotarProject** [comment]
Hi, sorry for my delay.

You can send a last line of Apache ``error_log`` or PHP error log after you see this error ?

At your disposal,
Joseph

**Comment by flanesi** [comment]
Sorry, but I do not have access to apache and PHP logs on this site.

**Comment by LotarProject** [comment]
Ciao, parlo in italiano che faccio prima :D

Se hai accesso al pannello di gestione del servizio hosting su Aruba puoi vedere gli ultimi log di errore (https://guide.hosting.aruba.it/hosting/linux/servizi-inclusi-creazione-sito-web/mostra-log-errori.aspx).

Giuseppe

**Comment by flanesi** [comment]
Sicuramente meglio in Italiano .... :D

Questo l'errore:
```
[Thu Oct 05 18:37:46 2017] [error] [client 87.2.110.220:63091] - www.flanesi.it - AH01215: Deprecated: Directive 'magic_quotes_gpc' is deprecated in PHP 5.3 and greater in Unknown on line 0
: /web/htdocs/www.flanesi.it/home/blog/index.php, referer http://www.flanesi.it/doku/lib/plugins/bootswrapper/exe/popup.php?ns=&edid=wiki__text
```

**Comment by LotarProject** [comment]
Effettivamente ho lo stesso problema su un server su Aruba (ma a me non logga niente), ma la cosa ancora più strana che anche altri plugin DokuWiki che aprono popup, su Aruba vanno in errore. Non vorrei che è collegato alla versione di PHP di Aruba o al fatto che (nel mio caso) c'è un ``.htaccess`` nella directory principale per il sito principale.

**Comment by flanesi** [comment]
Se può essere utile anch'io ho un .htaccess che regola gli accessi nella directory principale.
Come si vede dall'errore la mia versione di PHP è la 5.3.

Ho notato che anche nel mio caso ho altri plugin che danno errore nel log ....
