### ISSUE TITLE
Ampersand in title= dont work. 

### ISSUE THREAD

**Issue by MvErven** [giterlizzi/dokuwiki-plugin-bootswrapper#92]
Having an ampersand in the title of a panel does not work.

`<panel type="info" title="Beer & Co"> `

Even if I try "Beer_&_Co" it breaks the panel.

**Comment by l0xy** [comment]
I'm also getting the error 
> Bootstrap Wrapper - Malformed tag `<panel title="command >`. Please check your code!

when I try to use the following code:
`<panel title="command > output.txt"> ... </panel>`

I'm having trouble with `>` as well as the `&` mentioned in the OP
Is there an escape sequence I'm missing? o.O

**Comment by giterlizzi** [comment]
The previous fix convert the "ampersand" character into "&amp;" HTML entity. For other HTML/XML special character use this entities:
- ```&lt;``` (<),
- ```&amp;``` (&)
- ```&gt;``` (>)
- ```&quot;``` (")
- ```&apos;``` (')

This is a sample:
```<panel type="info" title="HTML entities &amp; &gt; &lt">```
